#! /bin/bash

# GROUP_NAME
export GRP="GROUP_NAME"

# uncompress
uncompress

# clear files
find . -name '*.DS_Store' -type f -delete
find . -name '*.url' -type f -delete
find . -name '*.txt' -type f -delete

# clear COMPLETE tags
find . -name \"*[${GRP}]*COMPLETE*[${GRP}]*\" -type f -delete

# set dates on directories with COMPLETE tags
for i in $(ls); do
  fixdir "${i}"
  fixdate "${i}"
  shared_check "${i}"
  fixdir "${i}"
done

exit 0
