#! /bin/bash

# GROUP_NAME
export GRP="GROUP_NAME"

# uncompress
uncompress

declare -a StringArray=(
                        '*.DS_Store'
                        '*.url'
                        '*.txt'
                        \"*[${GRP}]*COMPLETE*[${GRP}]*\"
                        )

for val in ${StringArray[@]}; do
  find . -name ${val} -type f -delete
done

for i in $(ls); do
  m3u_info "${i}"
  set_date "${i}"
done

exit 0
