#! /bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
LIGHT_GREY='\033[0;37m'
DARK_GREY='\033[1;30m'
NC='\033[0m' # No Color

dir=$1

if [ -z "${dir}" ]; then
    echo "Missing directory parameter. Usage: fix_date <DIRECTORY>"
    exit 1
fi

if [ ! -d "${dir}" ]; then
    exit 1
fi

if [[ `ls "${dir}/" | wc -l | bc` -eq 0 ]]; then
    exit 1
fi

if [ -d ${dir} ]; then

  # set folder dates
  last_file=`ls -1a ${dir} | grep -v -e "^\[${GRP}\]" | tail -n1`
  folder_date=`GetFileInfo -m "${dir}/${last_file}"`
  SetFile -d "${folder_date}" "${dir}"
  SetFile -m "${folder_date}" "${dir}"

  # set files dates
  date=`GetFileInfo -d "${dir}"`
  for i in $(ls -Ap ${dir} | grep -v -e "^\[${GRP}\]"); do
    SetFile -d "${date}" ${dir}/${i}
    SetFile -m "${date}" ${dir}/${i}
  done

  echo -e "${DARK_GREY}${date} ${NC}${LIGHT_GREY}${dir}${NC} ${GREEN}✓${NC}"

fi

exit 0
