#! /bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
LIGHT_GREY='\033[0;37m'
DARK_GREY='\033[1;30m'
NC='\033[0m' # No Color

dir=$1

if [ -z "${dir}" ]; then
    echo "Missing directory parameter. Usage: ~/.fixdate <DIRECTORY>"
    exit 1
fi

if [ ! -d "${dir}" ]; then
    exit 1
fi

if [[ `ls "${dir}/" | wc -l | bc` -eq 0 ]]; then
    exit 1
fi

date=`/usr/bin/GetFileInfo -d "${dir}"`

for i in $(ls -Ap ${dir} | grep -v -e "^\[${GRP}\]"); do
    /usr/bin/SetFile -d "${date}" ${dir}/${i}
    /usr/bin/SetFile -m "${date}" ${dir}/${i}
done

echo "${DARK_GREY}${date} ${NC}${LIGHT_GREY}${dir}${NC} ${GREEN}✓${NC}"

exit 0
