#!/bin/bash

dir=$1

if [ -z "${dir}" ]; then
    echo "Missing directory parameter. Usage: m3u_info <DIRECTORY>"
    exit 1
fi

if [ ! -d "${dir}" ]; then
    exit 1
fi

if [[ `ls "${dir}/" | wc -l | bc` -eq 0 ]]; then
    exit 1
fi

validate_ext ${dir} "m3u" create_info

exit 0
