#!/bin/bash

currenttime=$(date "+%Y.%m.%d-%H.%M.%S")
mkdir "deleted-${currenttime}"

rar_count=`ls | grep '\.rar$' --color=never | wc -l`

if [ ${rar_count} -gt 0 ]; then
    ls | grep '\.rar$' --color=never | xargs -I '{}' rar x -y '{}' 1>/dev/null
    ls | grep '\.rar$' --color=never | xargs -I '{}' mv '{}' "deleted-${currenttime}"
fi

tar_count=`ls | grep '\.tar$' --color=never | wc -l`

if [ ${tar_count} -gt 0 ]; then
    ls | grep '\.tar$' --color=never | xargs -I '{}' tar xf '{}' 1>/dev/null
    ls | grep '\.tar$' --color=never | xargs -I '{}' mv '{}' "deleted-${currenttime}"
fi

mv "deleted-${currenttime}" ~/.Trash/.

exit 0
